### PR TITLE
Config cli prompt

### PR DESCRIPTION
**Pull request by Jirubizu**
Add a CLI interface for the config generation. Also used rustfmt to format the code

### CODE REVIEW

**Review by AltF02 — APPROVED** [review]
Lgtm! Sorry for late reply was busy past few days. Will request dylan's review if possible

**Comment by AltF02** [comment]
If possible could you edit README.md to fit the new cli system?

**Comment by Jirubizu** [comment]
Alright updated the Read me, tell me if that's better?

**Review by AltF02 — APPROVED** [review]
Yeah looks good!, I'll merge as dylan is not responding

**Pull request merged**
